// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAzKPQkdR2HOSwdMT8l_iU1maCJWCtGlA',
    appId: '1:960263285993:web:c4507558ae6b317a065478',
    messagingSenderId: '960263285993',
    projectId: 'cmsc23-todo-app-adcordero',
    authDomain: 'cmsc23-todo-app-adcordero.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-adcordero.appspot.com',
    measurementId: 'G-MDLWV3P00Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIREkEjnuPL_05rT358wn1idMx6ElyHSM',
    appId: '1:960263285993:android:38ea3f3f1e3a7ee5065478',
    messagingSenderId: '960263285993',
    projectId: 'cmsc23-todo-app-adcordero',
    storageBucket: 'cmsc23-todo-app-adcordero.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIyb_Kpjot1-fKTuLfLjeTHjOohmwFIik',
    appId: '1:960263285993:ios:8029a79549ebb1d8065478',
    messagingSenderId: '960263285993',
    projectId: 'cmsc23-todo-app-adcordero',
    storageBucket: 'cmsc23-todo-app-adcordero.appspot.com',
    iosClientId: '960263285993-9prgti4gq6q5kq3gg346qg1i2j3mt3cs.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIyb_Kpjot1-fKTuLfLjeTHjOohmwFIik',
    appId: '1:960263285993:ios:8029a79549ebb1d8065478',
    messagingSenderId: '960263285993',
    projectId: 'cmsc23-todo-app-adcordero',
    storageBucket: 'cmsc23-todo-app-adcordero.appspot.com',
    iosClientId: '960263285993-9prgti4gq6q5kq3gg346qg1i2j3mt3cs.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
